# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='models',
            old_name='system_id',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='model_id',
            new_name='model',
        ),
    ]
